from .schema import (
    AnswerTokenEvent,
    ChatHistory,
    ChatMessage,
    ClarificationEvent,
    DoneEvent,
    ErrorEvent,
    InvokeResponse,
    StreamInput,
    SystemStatusEvent,
    ToolCall,
    ToolCallEvent,
    ToolResultEvent,
    UserInput,
)
from .dto import (
    AnswerResponse,
    Citation,
    Decision,
    ERROR_CODES,
    ErrorDetail,
    EvidenceHit,
    EvidenceRequest,
    EvidenceWindow,
    SearchRequest,
    SearchResponse,
    ServiceMetadata,
    Span,
    Usage,
)

__all__ = [
    # 公共证据/检索 DTO（L2 契约，HTTP/MCP 共用）
    "EvidenceHit",
    "Span",
    "SearchRequest",
    "SearchResponse",
    "EvidenceRequest",
    "EvidenceWindow",
    "AnswerResponse",
    "Citation",
    "Usage",
    "Decision",
    "ServiceMetadata",
    "ErrorDetail",
    "ERROR_CODES",
    # 旧 SSE/对话 schema（Day 3 迁移后退役）
    "UserInput",
    "StreamInput",
    "ToolCall",
    "ChatMessage",
    "ChatHistory",
    "InvokeResponse",
    "AnswerTokenEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "SystemStatusEvent",
    "ClarificationEvent",
    "DoneEvent",
    "ErrorEvent",
]
